- hosts: webservers
  vars: 
    root_dir: /usr/share/nginx/
    nginx_port: 80  
  tasks:
    - name: apt update
      ansible.builtin.apt:
        name: apt
        state: present
        update_cache: yes
      become: yes
      tags: install nginx  
    
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes
      tags: install nginx


    - name: update index.hmtl nginx
      ansible.builtin.template:
        src: "templates/index.html.conf.j2"
        dest: "{{root_dir}}html/index.html"
      notify: 
        - restart nginx
      become: yes

    - name: update config nginx
      ansible.builtin.template:
         src: "templates/nginx.conf.j2"
         dest: /etc/nginx/nginx.conf
      notify:
         - restart nginx
      become: yes  

  handlers:
        - name: restart nginx
          ansible.builtin.service:
            name: nginx
            state: reloaded
          become: yes
